---
- name: playbook that executes ssh-copy-id in vms
  hosts: localhost
  vars:
    passwd: "Redhat01." #we could use a vault to protect this
    group: all  #default group to execute ssh-copy-id
  remote_user: root
  tasks:
  - name: install sshpass
    yum:
      name: sshpass
      state: latest 
  - name: deploy key 
    command: sshpass -p "{{ passwd }}" ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@'{{ item }}'
    loop: "{{ groups['all'] }}"
